require PR title validation to pass

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -15,4 +15,19 @@ jobs:
       - uses: actions/checkout@v4
       - uses: ./.github/actions/enforce-convco
         with:
-          github-token: ${{ secrets.GITHUB_TOKEN }} 
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+
+  required:
+    if: always()
+    needs:
+      - check-pr-title
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if required jobs passed or were skipped
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" ]]; then
+            echo "One or more required jobs failed"
+            exit 1
+          else
+            echo "All required jobs have passed or were skipped!"
+          fi
